OUTPUT_ROM_FILENAME = Dadish.gbc

GBDK_PATH = Build/GBDK-2020

LCC_PATH = $(GBDK_PATH)/bin/lcc
PNG2ASSET_PATH = $(GBDK_PATH)/bin/png2asset

SOURCE_DIRECTORY_PATH = Source
RESOURCES_DIRECTORY_PATH = Resources
OBJECTS_DIRECTORY_PATH = Objects
OUTPUT_DIRECTORY_PATH = Output

OBJECTS_RESOURCES_SUBDIRECTORY_PATH = $(OBJECTS_DIRECTORY_PATH)/$(RESOURCES_DIRECTORY_PATH)
OUTPUT_ROM_FILE_PATH = $(OUTPUT_DIRECTORY_PATH)/$(OUTPUT_ROM_FILENAME)

LCC_INCLUDE_OBJECTS_DIRECTORY_PATH = -I$(OBJECTS_DIRECTORY_PATH)
LCC_MEMORY_BANK_CONTROLLER_TYPE_FLAG = -Wl-yt0x1B
LCC_GBC_EXCLUSIVE_MODE_FLAG = -Wm-yC
LCC_AUTOBANK_FLAG = -autobank
LCC_ADDITIONAL_MBC_AND_AUTOBANKING_FLAGS = -Wl-j -Wm-yoA -Wm-ya4 -Wb-ext=.rel -Wb-v

LCC_FLAGS = \
	$(LCC_INCLUDE_OBJECTS_DIRECTORY_PATH) \
	$(LCC_MEMORY_BANK_CONTROLLER_TYPE_FLAG) \
	$(LCC_GBC_EXCLUSIVE_MODE_FLAG) \
	$(LCC_AUTOBANK_FLAG) \
	$(LCC_ADDITIONAL_MBC_AND_AUTOBANKING_FLAGS)

METASPRITE_PNG_IMAGE_FILES = $(wildcard $(RESOURCES_DIRECTORY_PATH)/*.png)

METASPRITE_INTERMEDIATE_C_SOURCE_FILES = $(patsubst \
	$(RESOURCES_DIRECTORY_PATH)/%.png, \
	$(OBJECTS_RESOURCES_SUBDIRECTORY_PATH)/%.c, \
	$(METASPRITE_PNG_IMAGE_FILES))

METASPRITE_OBJECT_FILES = $(patsubst \
	%.c, \
	$(OBJECTS_DIRECTORY_PATH)/%.o, \
	$(notdir $(METASPRITE_INTERMEDIATE_C_SOURCE_FILES)))

C_SOURCE_FILES = $(wildcard $(SOURCE_DIRECTORY_PATH)/*.c) $(wildcard $(RESOURCES_DIRECTORY_PATH)/*.c)
S_SOURCE_FILES = $(wildcard $(SOURCE_DIRECTORY_PATH)/*.s)

OBJECT_FILES = \
	$(patsubst $(SOURCE_DIRECTORY_PATH)/%.c, $(OBJECTS_DIRECTORY_PATH)/%.o, $(filter $(SOURCE_DIRECTORY_PATH)/%.c, $(C_SOURCE_FILES))) \
	$(patsubst $(RESOURCES_DIRECTORY_PATH)/%.c, $(OBJECTS_DIRECTORY_PATH)/%.o, $(filter $(RESOURCES_DIRECTORY_PATH)/%.c, $(C_SOURCE_FILES))) \
	$(patsubst $(SOURCE_DIRECTORY_PATH)/%.s, $(OBJECTS_DIRECTORY_PATH)/%.o, $(S_SOURCE_FILES))

all: gbc

$(OBJECTS_RESOURCES_SUBDIRECTORY_PATH)/%.c: $(RESOURCES_DIRECTORY_PATH)/%.png
	$(PNG2ASSET_PATH) $< -sh 48 -spr8x8 -noflip -c $@

$(OBJECTS_DIRECTORY_PATH)/%.o: $(OBJECTS_RESOURCES_SUBDIRECTORY_PATH)/%.c
	$(LCC_PATH) $(LCC_FLAGS) -c -o $@ $<

$(OBJECTS_DIRECTORY_PATH)/%.o: $(SOURCE_DIRECTORY_PATH)/%.c
	$(LCC_PATH) $(LCC_FLAGS) -c -o $@ $<

$(OBJECTS_DIRECTORY_PATH)/%.o: $(RESOURCES_DIRECTORY_PATH)/%.c
	$(LCC_PATH) $(LCC_FLAGS) -c -o $@ $<

$(OBJECTS_DIRECTORY_PATH)/%.o: $(SOURCE_DIRECTORY_PATH)/%.s
	$(LCC_PATH) $(LCC_FLAGS) -c -o $@ $<

$(OUTPUT_ROM_FILE_PATH): $(METASPRITE_OBJECT_FILES) $(OBJECT_FILES)
	$(LCC_PATH) $(LCC_FLAGS) -o $@ $^

gbc: $(OUTPUT_ROM_FILE_PATH)

clean:
	rm -rf $(OBJECTS_DIRECTORY_PATH) $(OUTPUT_DIRECTORY_PATH)

$(shell mkdir -p $(OBJECTS_DIRECTORY_PATH) $(OBJECTS_RESOURCES_SUBDIRECTORY_PATH) $(OUTPUT_DIRECTORY_PATH))
